UniversityManagement.Web/Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagement.Entities;
using UniversityManagement.Service;
using UniversityManagement.Web.ViewModel;

namespace UniversityManagement.Web.Controllers
{
    public class CourseAssignController : Controller
    {
        // GET: CourseAssign
        public ActionResult Index()
        {
            CourseAssignListingViewModel viewModel = new CourseAssignListingViewModel();
            viewModel.courseassigns = CourseAssignService.Instance.AllAssignCoursesInfo();
            return View(viewModel);
        }

        public ActionResult Create()
        {
            CourseAssignViewModel viewModel = new CourseAssignViewModel();

            viewModel.departments = DepartmentService.Instance.AllDepartmentsInfo();
            viewModel.teachers = TeacherService.Instance.AllTeachersInfo();
            viewModel.courses = CourseService.Instance.AllCoursesInfo();


            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(CourseAssignViewModel viewModel)
        {
            CourseAssign newcourseassign = new CourseAssign();

            newcourseassign.DepartmentId = viewModel.DepartmentId;
            newcourseassign.TeacherId = viewModel.TeacherId;

            newcourseassign.Teacher.Credit = viewModel.Teacher.Credit;
            newcourseassign.RemainCredit = viewModel.Teacher.Credit - viewModel.Course.Credit;

            newcourseassign.CourseId = viewModel.CourseId;
            newcourseassign.Course.Name = viewModel.Course.Name;
            newcourseassign.Credit = newcourseassign.Credit;


            CourseAssignService.Instance.SaveCourse(newcourseassign);
            return RedirectToAction("Index");

        }
    }
}

UniversityManagement.Web/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagement.Entities;
using UniversityManagement.Service;
using UniversityManagement.Web.ViewModel;

namespace UniversityManagement.Web.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult Index()
        {
            CourseListingViewModel viewModel = new CourseListingViewModel();
            viewModel.Courses = CourseService.Instance.AllCoursesInfo();
            return View(viewModel);
        }

        
        public ActionResult Create()
        {
            CourseViewModelCreate viewModel = new CourseViewModelCreate();
            viewModel.departments = DepartmentService.Instance.AllDepartmentsInfo();
            viewModel.Semesters = Enum.GetValues(typeof(Semester)).Cast<Semester>().ToList();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(CourseViewModelCreate viewModel)
        {
            Course newCourse = new Course();

            newCourse.Code = viewModel.Code;
            newCourse.Name = viewModel.Name;
            newCourse.Credit = viewModel.Credit;
            newCourse.Description = viewModel.Description;

            newCourse.DepartmentId = viewModel.DepartmentId;
            newCourse.Semester = (Semester)Enum.Parse(typeof(Semester),viewModel.Semester.ToString());


            CourseService.Instance.SaveCourse(newCourse);
            return RedirectToAction("Index");
        }

    }
}

UniversityManagement.Web/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagement.Entities;
using UniversityManagement.Service;
using UniversityManagement.Web.ViewModel;

namespace UniversityManagement.Web.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            DepartmentViewModel viewModel = new DepartmentViewModel();

            viewModel.departments = DepartmentService.Instance.AllDepartmentsInfo();

            return View(viewModel);
        }
        public ActionResult Create()
        {
            return View();
        } 
        [HttpPost]
        public ActionResult Create(Department department)
        {
            Department newDepartment = new Department();
            newDepartment.Code = department.Code;
            newDepartment.Name = department.Name;

            DepartmentService.Instance.SaveDept(newDepartment);
            return RedirectToAction("Index");
        }
    }
}

UniversityManagement.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UniversityManagement.Web/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagement.Entities;
using UniversityManagement.Service;
using UniversityManagement.Web.ViewModel;

namespace UniversityManagement.Web.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Index()
        {
            TeacherListingViewModel viewModel = new TeacherListingViewModel();
            viewModel.Teachers = TeacherService.Instance.AllTeachersInfo();
            return View(viewModel);
        }

        public ActionResult Create()
        {
            TeacherViewModel viewModel = new TeacherViewModel();

            viewModel.departments = DepartmentService.Instance.AllDepartmentsInfo();
            viewModel.designations = DesignationService.Instance.AllDesignationInfo();

            
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(TeacherViewModel viewModel)
        {
            Teacher newTeacher = new Teacher();

            newTeacher.Name = viewModel.Name;
            newTeacher.Address = viewModel.Address;
            newTeacher.Email = viewModel.Email;
            newTeacher.ContactNo = viewModel.ContactNo;

            newTeacher.DepartmentId = viewModel.DepartmentId;
            newTeacher.DesignationId =viewModel.DesignationId;
            
            newTeacher.Credit = viewModel.Credit;
            
            TeacherService.Instance.SaveTeacher(newTeacher);
            return RedirectToAction("Index");
        }
    }
}

UniversityManagement.Web/Views/Course/Create.cshtml
@model UniversityManagement.Web.ViewModel.CourseViewModelCreate

@{
    ViewBag.Title = "Create";
}

<h2>Save Course</h2>

<form id="createCourse">
    <div class="row">
        <div class="col-md-8">
            <label>Code</label>
            <input name="Code" />
            <br />
            <label>Name</label>
            <input name="Name" />
            <br />
            <label>Credit</label>
            <input name="Credit" />
            <br />
            <label>Description</label>
            <input name="Description" />

            <div class="form-group">

                <label>Department</label>

                <select class="form-control" name="DepartmentId">
                    @foreach (var dept in Model.departments)
                    {
                        <option value="@dept.Id">@dept.Name</option>
                    }
                </select>

            </div>

            <div class="form-group">
                <label>Semester</label>
                @Html.EnumDropDownListFor(
                    x => x.Semester,
                    "Select semester",
                    new { @class = "form-control" })

            </div>

            <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-danger">Cancel</button>
        </div>
    </div>
</form>
<script>
    $("#saveBtn").click(function () {
        $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Course")',
                data: $("#createCourse").serialize()
            })
            .done(function (response) {
                console.log(response);
                window.location.href = '@Url.Action("Index", "Course")';
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
            });
    });
</script>

UniversityManagement.Web/Views/Course/Index.cshtml
@model UniversityManagement.Web.ViewModel.CourseListingViewModel

@{
    ViewBag.Title = "Index";
}

<h2>View All Courses</h2>

<table class="table">
    <thead>
    <tr>
        <td>Code</td>
        <td>Name</td>
        <td>Semester</td>
    </tr>
    </thead>
    <tbody>
    @foreach (var course in Model.Courses)
    {
        <tr>
            <td>@course.Code</td>
            <td>@course.Name</td>
            <td>@course.Semester</td>
        </tr>
    }

    </tbody>
</table>

UniversityManagement.Web/Views/CourseAssign/Create.cshtml
@model UniversityManagement.Web.ViewModel.CourseAssignViewModel


@{
    ViewBag.Title = "Create";
}

<h2>Create Assign</h2>

<form id="createTeacher">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Department</label>
                <select class="form-control" name="DepartmentId">
                    @foreach (var dept in Model.departments)
                    {
                        <option value="@dept.Id">@dept.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Teacher</label>
                <select class="form-control" name="TeacherId">
                    @foreach (var teacher in Model.teachers)
                    {
                        <option value="@teacher.Id">@teacher.Name</option>
                    }
                </select>
            </div>
            <br />
            <label>Credit to be taken</label>
            <input name="TakenCredit" />
            <br />
            <label>Remaining Credit</label>
            <input name="RemainCredit" />
            <br />
            <div class="form-group">
                <label>Course Code</label>
                <select class="form-control" name="CourseId">
                    @foreach (var course in Model.courses)
                    {
                        <option value="@course.Id">@course.Name</option>
                    }
                </select>
            </div>
            <br />
            <label>Name</label>
            <input name="Name" />
            <br />
            <label>Credit</label>
            <input name="Credit" />
            <br />

            <button id="saveBtn" type="button" class="btn btn-primary">Assign</button>
            <button type="reset" class="btn btn-danger">Cancel</button>

        </div>
    </div>
</form>


<script>
    $("#saveBtn").click(function () {
        $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "CourseAssign")',
                data: $("#createTeacher").serialize()
            })
            .done(function (response) {
                console.log(response);
                window.location.href = '@Url.Action("Index", "CourseAssign")';
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
            });
    });
</script>

UniversityManagement.Web/Views/Department/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<form id="createDept">
    <div class="row">
        <div class="col-md-8">
            <label>Code</label>
            <input name="Code" />
            <br />
            <label>Name</label>
            <input name="Name" />

            <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-danger">Cancel</button>
        </div>
    </div>
</form>

<script>
    $("#saveBtn").click(function () {
        $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Department")',
                data: $("#createDept").serialize()
            })
            .done(function (response) {
                console.log(response);
                window.location.href = '@Url.Action("Index", "Department")';
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
            });
    });
</script>

UniversityManagement.Web/Views/Department/Index.cshtml
@model UniversityManagement.Web.ViewModel.DepartmentViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View All Departments</h2>
<table class="table">
    <thead>
    <tr>
        <td>Code</td>
        <td>Name</td>
    </tr>
    </thead>
    <tbody>
    @foreach (var dept in Model.departments)
    {
        <tr>
            <td>@dept.Code</td>
            <td>@dept.Name</td>
        </tr>
    }

    </tbody>
</table>

UniversityManagement.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UniversityManagement.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UniversityManagement.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

UniversityManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>

UniversityManagement.Web/Views/Teacher/Create.cshtml
@model UniversityManagement.Web.ViewModel.TeacherViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Save Teacher</h2>

<form id="createTeacher">
    <div class="row">
        <div class="col-md-8">
            <label>Name</label>
            <input name="Name" />
            <br />
            <label>Address</label>
            <input name="Address" />
            <br />
            <label>Email</label>
            <input name="Email" />
            <br />
            <label>Contact No</label>
            <input name="ContactNo" />
            <br />
            <label>Credit</label>
            <input name="Credit" />

            @*<div class="form-group">
                @Html.LabelFor(model => model.Credit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Credit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <label>Department</label>
                <select class="form-control" name="DepartmentId">
                    @foreach (var dept in Model.departments)
                    {
                        <option value="@dept.Id">@dept.Name</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label>Designation</label>
                <select class="form-control" name="DesignationId">
                    @foreach (var designation in Model.designations)
                    {
                        <option value="@designation.Id">@designation.DesignationName</option>
                    }
                </select>
            </div>


            <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-danger">Cancel</button>
        </div>
    </div>
</form>

<script>
    $("#saveBtn").click(function () {
        $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Teacher")',
                data: $("#createTeacher").serialize()
            })
            .done(function (response) {
                console.log(response);
                window.location.href = '@Url.Action("Index", "Teacher")';
            })
            .fail(function (xmlHttpRequest, textStatus, errorThrown) {
            });
    });
</script>

UniversityManagement.Web/Views/Teacher/Index.cshtml
@model UniversityManagement.Web.ViewModel.TeacherListingViewModel

@{
    ViewBag.Title = "Index";
}



<h2>View All Teacher</h2>
<table class="table">
    <thead>
        <tr>
            <td>Name</td>
            <td>Address</td>
            <td>Email</td>
            <td>Contact No</td>
            <td>Designation</td>
            <td>Department</td>
            <td>Credit to be taken </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var teacher in Model.Teachers)
        {
            <tr>
                <td>@teacher.Name</td>
                <td>@teacher.Address</td>
                <td>@teacher.Email</td>
                <td>@teacher.ContactNo</td>
                <td>@teacher.Designation.DesignationName</td>
                <td>@teacher.Department.Name</td>
                <td>@teacher.Credit</td>
            </tr>
        }

    </tbody>
</table>